# KNN(K NEAREST NEIGHBOUR)

KNN is a supervised learning 
it also called as lazy learning

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#importing dataset
data=pd.read_csv('dataset/User_Data.csv')

In [3]:
#extracting independent and dependent variable
x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values
print(x[:10])

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]]


In [4]:
# splitting dataset into train and test set
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25,random_state=0)

In [5]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.transform(xtest)

print(xtrain[:10])

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]]


# Based on matrics -- minkowski,manhattan,euclidean

In [6]:
## minkowski 

#fitting KNN classifier to the training set

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(xtrain,ytrain)

KNeighborsClassifier()

In [7]:
## manhattan

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='manhattan',p=2)
classifier.fit(xtrain,ytrain)

KNeighborsClassifier(metric='manhattan')

In [8]:
# Euclidean

from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5,metric='euclidean',p=2)
classifier.fit(xtrain,ytrain)

KNeighborsClassifier(metric='euclidean')

In [9]:
#predicting the test set result

y_pred=classifier.predict(xtest)

y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [10]:
#creating the confusion matrix
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(ytest,y_pred)
print("confusion matrix:\n",cm)

confusion matrix:
 [[64  4]
 [ 3 29]]


In [11]:
from sklearn.metrics import accuracy_score
print("accuracy:",accuracy_score(ytest,y_pred))

accuracy: 0.93


In [12]:
from sklearn.metrics import precision_score
print("precision:",precision_score(ytest,y_pred))

precision: 0.8787878787878788
