# SUPPORT VECTOR MACHINE

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('dataset/User_Data.csv')

In [3]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
# PREPROCESSING

# map will replace the value based on column index
data['Gender']=data['Gender'].map({'Male':0,'Female':1,}).astype(float)
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510     0.0   19            19000          0
1    15810944     0.0   35            20000          0
2    15668575     1.0   26            43000          0
3    15603246     1.0   27            57000          0
4    15804002     0.0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863     1.0   46            41000          1
396  15706071     0.0   51            23000          1
397  15654296     1.0   50            20000          1
398  15755018     0.0   36            33000          0
399  15594041     1.0   49            36000          1

[400 rows x 5 columns]

In [5]:
x=data.iloc[:,[2,3]]
print(x)
y=data.iloc[:,4]
y

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]


0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [6]:

#print the values in that location
# :--- print all the values in the rows

x=data.iloc[:,[2,3]].values
y=data.iloc[:,4].values

In [7]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.25)

#0.25--indicates the percentage of the data that should be held over for testing.

In [11]:
# if we run the model without standrad scaler then the accuracy will be low
# standard scaler will work only on numeric data

from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.transform(xtest)

print(xtrain[0:10,:])
print(xtest[0:10,:])

[[-0.46589516 -0.87379331]
 [ 0.67043451  1.73051394]
 [ 1.99615245 -1.22103428]
 [-0.08711861 -0.26612162]
 [-0.93936586 -0.35293186]
 [-1.69691897 -1.01847705]
 [ 1.71207004 -0.32399511]
 [ 1.52268176  0.94922176]
 [ 1.90145831  2.10669165]
 [-0.18181275 -1.10528729]]
[[ 0.95451692 -1.10528729]
 [-0.65528344 -1.5393385 ]
 [ 0.19696381 -0.29505837]
 [-0.27650689  2.19350189]
 [ 0.10226967 -0.84485656]
 [ 0.19696381 -0.41080535]
 [ 0.67043451  0.22580308]
 [-0.27650689  0.57304405]
 [ 0.85982278 -0.61336258]
 [-0.27650689  0.02324585]]


In [12]:
# logistic regression

from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(xtrain,ytrain)

LogisticRegression(random_state=0)

In [13]:
# to save the file of the model

# pickle used to store and read the binary data or files
#store--dumb
#read--load

import pickle
with open('logistic_model.pkl','wb') as file: # wb--write binary
    pickle.dump(classifier,file)
with open('logistic_model.pkl', 'rb') as f:
    classifier=pickle.load(f)
    

In [14]:
y_pred=classifier.predict(xtest)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(ytest,y_pred)
print("confusion matrix:\n",cm)

confusion matrix:
 [[67  4]
 [ 8 21]]


In [16]:
from sklearn.metrics import accuracy_score
print("acuracy:",accuracy_score(ytest,y_pred))

acuracy: 0.88


In [17]:
from sklearn.metrics import precision_score
print("precision:",precision_score(ytest,y_pred))

precision: 0.84
